import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
	description: 'Generated by create next app',
	title: 'Car Dealer App',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>): React.JSX.Element {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	)
}
